# -*- coding: utf-8 -*-
import scrapy


class SpiderSpider(scrapy.Spider):
    name = 'spider'
    allowed_domains = ['greenweez.com']
    start_urls = [
        'https://www.greenweez.com/aperitifs-bio-c1107',
        'https://www.greenweez.com/superaliments-superfruits-c3245',
        'https://www.greenweez.com/thes-bio-et-infusions-c611',
        'https://www.greenweez.com/format-familial-economique-vrac-c3962',
        'https://www.greenweez.com/cuisine-du-monde-bio-c5453',
        'https://www.greenweez.com/selection-produits-veggie-celnat-c5117',
        'https://www.greenweez.com/boissons-vegetales-c1421',
        'https://www.greenweez.com/Jus-de-fruits-bio-c1324',
        'https://www.greenweez.com/jus-de-legumes-c3314',
        'https://www.greenweez.com/sodas-bio-c3271',
        'https://www.greenweez.com/vins-bio-c3269',
        'https://www.greenweez.com/bieres-bio-c1768',
        'https://www.greenweez.com/Alcools-bio-c4705',
        'https://www.greenweez.com/boisson-bien-etre-c5347',
        'https://www.greenweez.com/jus-de-grenade-c2295',
        'https://www.greenweez.com/sirops-bio-c1325',
        'https://www.greenweez.com/eau-de-coco-c3994',
        'https://www.greenweez.com/thes-glaces-c4678',
        'https://www.greenweez.com/eaux-aromatisees-bio-c5651',
        'https://www.greenweez.com/Lait-de-vache-et-chevre-c2638',
        'https://www.greenweez.com/epicerie-sans-gluten-c751',
        'https://www.greenweez.com/produits-vegetarien-vegan-bio-c987',
        'https://www.greenweez.com/poisson-viande-bio-c2182',
        'https://www.greenweez.com/petit-dejeuner-bio-c3279',
        'https://www.greenweez.com/legumes-et-plats-cuisines-bio-c746',
        'https://www.greenweez.com/huiles-alimentaires-bio-c1410',
        'https://www.greenweez.com/fruits-secs-et-purees-c1103',
        'https://www.greenweez.com/farines-bio-c743',
        'https://www.greenweez.com/epicerie-bio-sucree-c1060',
        'https://www.greenweez.com/condiments-aides-culinaires-c749',
        'https://www.greenweez.com/cereales-graines-bio-c736',
        'https://www.greenweez.com/boissons-vegetales-c1421',
        'https://www.greenweez.com/produits-frais-vegan-bio-c4055',
        'https://www.greenweez.com/fruits-et-legumes-bio-c4602',
        'https://www.greenweez.com/boulangerie-fraiche-c4166',
        'https://www.greenweez.com/boissons-fraiches-c4167',
        'https://www.greenweez.com/riz-pates-cereales-rayon-frais-c5211',
        'https://www.greenweez.com/conserves-du-rayon-frais-c5209',
        'https://www.greenweez.com/sauces-et-condiments-rayon-frais-c5208',
        'https://www.greenweez.com/epicerie-sucree-du-rayon-frais-c5210',
        'https://www.greenweez.com/repas-festif-c5115',
        'https://www.greenweez.com/promotion-dlc-courte-c4897',
        'https://www.greenweez.com/prix-engages-c4697',
        'https://www.greenweez.com/gros-conditionnements-pros-c4826',
        'https://www.greenweez.com/Poissonnerie-et-boucherie-c4060',
        'https://www.greenweez.com/charcuteries-bio-c4051',
        'https://www.greenweez.com/cremerie-c4042',
        'https://www.greenweez.com/charcuteries-bio-c4051',
        'https://www.greenweez.com/cremerie-c4042',
        'https://www.greenweez.com/fromages-bio-c4046',
        'https://www.greenweez.com/yaourts-et-desserts-bio-c4775',
        'https://www.greenweez.com/traiteur-c4050',
        'https://www.greenweez.com/desserts-lactes-bio-bebe-c2691',
        'https://www.greenweez.com/gouters-biscuits-bio-bebe-c1302',
        'https://www.greenweez.com/bouillies-bio-bebe-c881',
        'https://www.greenweez.com/cereales-bio-bebe-c633',
        'https://www.greenweez.com/huiles-bebe-bio-c3713',
        'https://www.greenweez.com/boissons-bebe-bio-c632',
        'https://www.greenweez.com/alimentation-enfants-bio-c3222',
        'https://www.greenweez.com/alimentation-bebe-sans-gluten-c3180',
        'https://www.greenweez.com/soupes-bio-bebe-c1303',
        'https://www.greenweez.com/petits-pots-bebe-du-soir-c2978',
        'https://www.greenweez.com/petits-pots-fruits-bebe-c2962',
        'https://www.greenweez.com/petits-pots-legumes-bebe-c2998',
        'https://www.greenweez.com/petits-pots-bebe-du-midi-c2971',
        'https://www.greenweez.com/preparations-vegetales-bebe-c2923',
        'https://www.greenweez.com/preparation-bio-au-lait-de-brebis-c2994',
        'https://www.greenweez.com/preparations-au-lait-de-chevre-bio-bebe-c2925',
        'https://www.greenweez.com/lait-infantile-bio-c631',
        'https://www.greenweez.com/soins-solaires-c49',
        'https://www.greenweez.com/hygiene-bebe-soin-maternite-c3030',
        'https://www.greenweez.com/couche-ecologique-c3012',
        'https://www.greenweez.com/soins-a-l-aloe-vera-c4810',
        'https://www.greenweez.com/argile-c1089',
        'https://www.greenweez.com/cosmetique-grand-format-c4913',
        'https://www.greenweez.com/cosmetique-vegan-c4716',
        'https://www.greenweez.com/cosmetique-ayurvedique-c3256',
        'https://www.greenweez.com/cosmetiques-a-faire-soi-meme-c2169',
        'https://www.greenweez.com/coffrets-cadeaux-c5204',
        'https://www.greenweez.com/soins-homme-c427',
        'https://www.greenweez.com/soins-du-corps-c101',
        'https://www.greenweez.com/soins-du-visage-c52',
        'https://www.greenweez.com/maquillage-c144',
        'https://www.greenweez.com/epilation-c1408',
        'https://www.greenweez.com/soins-des-cheveux-c85',
        'https://www.greenweez.com/douche-et-bain-c44',
        'https://www.greenweez.com/hygiene-c70',
        'https://www.greenweez.com/livres-maternite-education-c5821',
        'https://www.greenweez.com/fournitures-scolaires-c416',
        'https://www.greenweez.com/bracelet-collier-ambre-bebe-c816',
        'https://www.greenweez.com/linge-de-lit-bebe-enfant-c996',
        'https://www.greenweez.com/matelas-bebe-enfant-c638',
        'https://www.greenweez.com/chambre-et-mobilier-enfant-c521',
        'https://www.greenweez.com/transport-enfant-c1230',
        'https://www.greenweez.com/loisirs-creatifs-c1592',
        'https://www.greenweez.com/veilleuses-reveils-c51',
        'https://www.greenweez.com/jouets-sains-c40',
        'https://www.greenweez.com/chaussons-bebes-c2709',
        'https://www.greenweez.com/vetements-accessoires-c54',
        'https://www.greenweez.com/hygiene-soins-c96',
        'https://www.greenweez.com/couches-ecologiques-c74',
        'https://www.greenweez.com/allaitement-c2131',
        'https://www.greenweez.com/biberons-accessoires-c80',
        'https://www.greenweez.com/le-repas-de-bebe-c58',
        'https://www.greenweez.com/alimentation-bebe-c2108',
        'https://www.greenweez.com/entretien-des-wc-c785',
        'https://www.greenweez.com/desodorisants-c791',
        'https://www.greenweez.com/anti-insecte-c1205',
        'https://www.greenweez.com/anti-calcaire-c795',
        'https://www.greenweez.com/produits-nettoyants-pour-vitres-c786',
        'https://www.greenweez.com/accessoires-menagers-c3725',
        'https://www.greenweez.com/impermeabilisants-c1204',
        'https://www.greenweez.com/nettoyants-techniques-ecologiques-c796',
        'https://www.greenweez.com/Savon-noir-maison-c2368',
        'https://www.greenweez.com/nettoyants-multi-usages-c797',
        'https://www.greenweez.com/produits-vaisselle-c787',
        'https://www.greenweez.com/soin-du-linge-c3723',
        'https://www.greenweez.com/Savon-de-Marseille-Linge-c2367',
        'https://www.greenweez.com/lessives-ecologiques-c790',
        'https://www.greenweez.com/droguerie-ecologique-c3635',
        'https://www.greenweez.com/les-indispensables-c5229',
        'https://www.greenweez.com/materiel-medical-c2527',
        'https://www.greenweez.com/massage-kinesitherapie-c926',
        'https://www.greenweez.com/relaxation-detente-sommeil-c2459',
        'https://www.greenweez.com/sport-et-nutrition-c873',
        'https://www.greenweez.com/luminotherapie-c854',
        'https://www.greenweez.com/diffuseurs-d-huiles-essentielles-c1316',
        'https://www.greenweez.com/aromatherapie-c3642',
        'https://www.greenweez.com/digestion-transit-flore-c589',
        'https://www.greenweez.com/minceur-c601',
        'https://www.greenweez.com/parapharmacie-c2526',
        'https://www.greenweez.com/fleurs-de-bach-phytotherapie-elixirs-floraux-c595',
        'https://www.greenweez.com/phytotherapie-c3428',
        'https://www.greenweez.com/vitamines-mineraux-c2468',
        'https://www.greenweez.com/nez-gorge-oreille-c594',
        'https://www.greenweez.com/resistance-et-vitalite-c590',
        'https://www.greenweez.com/complements-alimentaires-c2522',
        'https://www.greenweez.com/zero-dechet-c5397',
        'https://www.greenweez.com/livres-vie-saine-c1330',
        'https://www.greenweez.com/mode-bio-c1491',
        'https://www.greenweez.com/appareils-de-mesure-c99',
        'https://www.greenweez.com/energie-c2972',
        'https://www.greenweez.com/Soldes-cosmetiques-c1356',
        'https://www.greenweez.com/soldes-cuisine-c1353',
        'https://www.greenweez.com/Soldes-enfant-c1351',
        'https://www.greenweez.com/Soldes-epicerie-c1352',
        'https://www.greenweez.com/Soldes-maison-c1349',
        'https://www.greenweez.com/Soldes-sante-c1355',
        'https://www.greenweez.com/rangement-c2284',
        'https://www.greenweez.com/peinture-bricolage-c1407',
        'https://www.greenweez.com/transport-ecologique-c30',
        'https://www.greenweez.com/traitement-de-l-eau-c27',
        'https://www.greenweez.com/traitement-de-l-air-c26',
        'https://www.greenweez.com/detecteur-anti-ondes-c55',
        'https://www.greenweez.com/lumiere-c25',
        'https://www.greenweez.com/decoration-c79',
        'https://www.greenweez.com/salle-de-bains-c81',
        'https://www.greenweez.com/chambre-c65',
        'https://www.greenweez.com/nature-activites-d-exterieur-c72',
        'https://www.greenweez.com/mobilier-exterieur-piscine-c1131',
        'https://www.greenweez.com/jardin-c92',
        'https://www.greenweez.com/animalerie-bio-c5150',
        'https://www.greenweez.com/livres-cuisine-c4746',
        'https://www.greenweez.com/cuisine-vegan-c4898',
        'https://www.greenweez.com/composteurs-et-poubelles-de-tri-c1882',
        'https://www.greenweez.com/chariots-de-courses-c1339',
        'https://www.greenweez.com/pour-emporter-c992',
        'https://www.greenweez.com/ustensiles-de-cuisine-c698',
        'https://www.greenweez.com/carafes-et-fontaines-c1288',
        'https://www.greenweez.com/conservation-c831',
        'https://www.greenweez.com/cuisson-vapeur-c702',
        'https://www.greenweez.com/cocottes-plat-a-four-c2171',
        'https://www.greenweez.com/poeles-sauteuses-c705',
        'https://www.greenweez.com/casseroles-faitouts-c706',
        'https://www.greenweez.com/germoirs-c700',
        'https://www.greenweez.com/deshydrateurs-alimentaires-c704',
        'https://www.greenweez.com/extracteurs-de-jus-c731',
        'https://www.greenweez.com/appareils-de-cuisine-c730'
    ]

    def parse(self, response):
        urls = response.xpath('//div[@class="rayon_img"]/div[@class="titre"]/a/@href').extract()
        for url in urls:
            yield scrapy.Request(url, callback=self.individual_page)

        # Calling next page
        next_page_url = response.xpath('//div[@id="page_list_content"]/ul[@class="pl_cat_pag"][1]/li[contains(.//@class, "linkwins selected")]/following-sibling::li[1]/a/@href').extract()
        yield scrapy.Request(next_page_url, callback=self.parse)


    def individual_page(self, response):
        base_price = response.xpath('//div[@class="prix_barre"]/text()').re_first('(\d+\,\d+)')
        discounted_price = response.xpath('//div[@class="fp_price_tag"]/text()').re_first('(\d+\,\d+)')
        product_name = response.xpath('//h1/span/text()').extract_first()
        category = response.xpath('//div[@class="fil_ariane_txt"]/ul/li/a[@class="fleche_souligne"]/span/text()').extract()

        fields = dict(base_price=base_price, discounted_price=discounted_price, product_name=product_name, category=category)

        yield fields